### PR TITLE
Patch to use sudo instead of su so password wont be asked so many times

### LINKED ISSUE #11: User account credential caching
Being prompted to enter the factorio user's password several times in a row is weird, and made me think something was broken. I think if `as_user` does `sudo -u $USERNAME` the user will only be prompted for the user password once while the credential is cached (by default, 5 minutes). I think it my also be helpful to explicitly say the password prompt is for $USER.

### PR DESCRIPTION
**Pull request by maikelwever**
Fixes #11 

@psihius please test.

### CODE REVIEW

**Comment by maikelwever** [comment]
Also travis itself seems broken, the PR doesnt seem to have anything to do with this.

**Comment by psihius** [comment]
@maikelwever 
Hmm, getting an error when I modify the `as_user` function to what's in the diff:

```
$ FENV=buildoff factorio version
sudo: /opt/factorio/factorio/bin/x64/factorio --version |egrep '^Version: [0-9\.]+' |egrep -o '[0-9\.]+' |head -n 1: command not found
```

Current user is root

**Comment by maikelwever** [comment]
@psihius can you test again?

Permissions seemed to be broken from the start when `factorio` script is called as a sudoed user, so now lots more commands need to be run `as_user` since it's now done more properly.

**Comment by psihius** [comment]
@maikelwever 
Looks like it works now, at least in my limited testing error is not shown any more.

**Comment by maikelwever** [comment]
Then I'd suggest we merge this.

I've also improved the DEBUG flag so it enabled bash tracing, then if something goes wrong we can figure out where and fix it.

**Pull request merged**
